[package]
name = "miniaudio_node"
version = "1.6.0"
edition = "2021"
description = "High-performance native audio playback for Node.js and Bun, built with Rust and rodio"
license = "MIT"
repository = "https://github.com/nglmercer/miniaudio-node"

[lib]
crate-type = ["cdylib"]
name = "miniaudio_node"

[dependencies]
napi = { version = "3.8.2", features = ["napi4", "serde-json", "async"] }
napi-derive = "3.5.1"
rodio = { version = "0.21.1", features = ["wav", "mp3", "flac", "vorbis"] }
cpal = "0.17.1"
base64 = "0.22"
rand = "0.9"
ringbuf = "0.4"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
opt-level = "z"
