/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface AudioDeviceInfo {
  id: string
  name: string
  isDefault: boolean
}
export declare function getSupportedFormats(): Array<string>
export declare function initializeAudio(): NapiResult
export declare class AudioPlayer {
  constructor()
  getDevices(): NapiResult
  loadFile(filePath: string): NapiResult
  play(): NapiResult
  pause(): NapiResult
  stop(): NapiResult
  setVolume(volume: number): NapiResult
  getVolume(): NapiResult
  isPlaying(): boolean
  getDuration(): NapiResult
  getCurrentTime(): NapiResult
}
