// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { readFileSync } = require('node:fs')
let nativeBinding = null
const loadErrors = []

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) {
      musl = isMuslFromReport()
    }
    if (musl === null) {
      musl = isMuslFromChildProcess()
    }
  }
  return musl
}

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-')

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')
  } catch {
    return null
  }
}

const isMuslFromReport = () => {
  let report = null
  if (typeof process.report?.getReport === 'function') {
    process.report.excludeNetwork = true
    report = process.report.getReport()
  }
  if (!report) {
    return null
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true
    }
  }
  return false
}

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl')
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false
  }
}

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err)
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./miniaudio_node.android-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('miniaudio_node-android-arm64')
        const bindingPackageVersion = require('miniaudio_node-android-arm64/package.json').version
        if (bindingPackageVersion !== '1.5.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.5.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./miniaudio_node.android-arm-eabi.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('miniaudio_node-android-arm-eabi')
        const bindingPackageVersion = require('miniaudio_node-android-arm-eabi/package.json').version
        if (bindingPackageVersion !== '1.5.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.5.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`))
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      if (process.config?.variables?.shlib_suffix === 'dll.a' || process.config?.variables?.node_target_type === 'shared_library') {
        try {
        return require('./miniaudio_node.win32-x64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('miniaudio_node-win32-x64-gnu')
        const bindingPackageVersion = require('miniaudio_node-win32-x64-gnu/package.json').version
        if (bindingPackageVersion !== '1.5.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.5.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      } else {
        try {
        return require('./miniaudio_node.win32-x64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('miniaudio_node-win32-x64-msvc')
        const bindingPackageVersion = require('miniaudio_node-win32-x64-msvc/package.json').version
        if (bindingPackageVersion !== '1.5.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.5.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      }
    } else if (process.arch === 'ia32') {
      try {
        return require('./miniaudio_node.win32-ia32-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('miniaudio_node-win32-ia32-msvc')
        const bindingPackageVersion = require('miniaudio_node-win32-ia32-msvc/package.json').version
        if (bindingPackageVersion !== '1.5.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.5.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./miniaudio_node.win32-arm64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('miniaudio_node-win32-arm64-msvc')
        const bindingPackageVersion = require('miniaudio_node-win32-arm64-msvc/package.json').version
        if (bindingPackageVersion !== '1.5.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.5.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    try {
      return require('./miniaudio_node.darwin-universal.node')
    } catch (e) {
      loadErrors.push(e)
    }
    try {
      const binding = require('miniaudio_node-darwin-universal')
      const bindingPackageVersion = require('miniaudio_node-darwin-universal/package.json').version
      if (bindingPackageVersion !== '1.5.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
        throw new Error(`Native binding package version mismatch, expected 1.5.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
      }
      return binding
    } catch (e) {
      loadErrors.push(e)
    }
    if (process.arch === 'x64') {
      try {
        return require('./miniaudio_node.darwin-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('miniaudio_node-darwin-x64')
        const bindingPackageVersion = require('miniaudio_node-darwin-x64/package.json').version
        if (bindingPackageVersion !== '1.5.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.5.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./miniaudio_node.darwin-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('miniaudio_node-darwin-arm64')
        const bindingPackageVersion = require('miniaudio_node-darwin-arm64/package.json').version
        if (bindingPackageVersion !== '1.5.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.5.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./miniaudio_node.freebsd-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('miniaudio_node-freebsd-x64')
        const bindingPackageVersion = require('miniaudio_node-freebsd-x64/package.json').version
        if (bindingPackageVersion !== '1.5.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.5.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./miniaudio_node.freebsd-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('miniaudio_node-freebsd-arm64')
        const bindingPackageVersion = require('miniaudio_node-freebsd-arm64/package.json').version
        if (bindingPackageVersion !== '1.5.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.5.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
          return require('./miniaudio_node.linux-x64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('miniaudio_node-linux-x64-musl')
          const bindingPackageVersion = require('miniaudio_node-linux-x64-musl/package.json').version
          if (bindingPackageVersion !== '1.5.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.5.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./miniaudio_node.linux-x64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('miniaudio_node-linux-x64-gnu')
          const bindingPackageVersion = require('miniaudio_node-linux-x64-gnu/package.json').version
          if (bindingPackageVersion !== '1.5.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.5.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
          return require('./miniaudio_node.linux-arm64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('miniaudio_node-linux-arm64-musl')
          const bindingPackageVersion = require('miniaudio_node-linux-arm64-musl/package.json').version
          if (bindingPackageVersion !== '1.5.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.5.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./miniaudio_node.linux-arm64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('miniaudio_node-linux-arm64-gnu')
          const bindingPackageVersion = require('miniaudio_node-linux-arm64-gnu/package.json').version
          if (bindingPackageVersion !== '1.5.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.5.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
          return require('./miniaudio_node.linux-arm-musleabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('miniaudio_node-linux-arm-musleabihf')
          const bindingPackageVersion = require('miniaudio_node-linux-arm-musleabihf/package.json').version
          if (bindingPackageVersion !== '1.5.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.5.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./miniaudio_node.linux-arm-gnueabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('miniaudio_node-linux-arm-gnueabihf')
          const bindingPackageVersion = require('miniaudio_node-linux-arm-gnueabihf/package.json').version
          if (bindingPackageVersion !== '1.5.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.5.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'loong64') {
      if (isMusl()) {
        try {
          return require('./miniaudio_node.linux-loong64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('miniaudio_node-linux-loong64-musl')
          const bindingPackageVersion = require('miniaudio_node-linux-loong64-musl/package.json').version
          if (bindingPackageVersion !== '1.5.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.5.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./miniaudio_node.linux-loong64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('miniaudio_node-linux-loong64-gnu')
          const bindingPackageVersion = require('miniaudio_node-linux-loong64-gnu/package.json').version
          if (bindingPackageVersion !== '1.5.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.5.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
          return require('./miniaudio_node.linux-riscv64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('miniaudio_node-linux-riscv64-musl')
          const bindingPackageVersion = require('miniaudio_node-linux-riscv64-musl/package.json').version
          if (bindingPackageVersion !== '1.5.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.5.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./miniaudio_node.linux-riscv64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('miniaudio_node-linux-riscv64-gnu')
          const bindingPackageVersion = require('miniaudio_node-linux-riscv64-gnu/package.json').version
          if (bindingPackageVersion !== '1.5.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 1.5.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./miniaudio_node.linux-ppc64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('miniaudio_node-linux-ppc64-gnu')
        const bindingPackageVersion = require('miniaudio_node-linux-ppc64-gnu/package.json').version
        if (bindingPackageVersion !== '1.5.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.5.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 's390x') {
      try {
        return require('./miniaudio_node.linux-s390x-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('miniaudio_node-linux-s390x-gnu')
        const bindingPackageVersion = require('miniaudio_node-linux-s390x-gnu/package.json').version
        if (bindingPackageVersion !== '1.5.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.5.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      try {
        return require('./miniaudio_node.openharmony-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('miniaudio_node-openharmony-arm64')
        const bindingPackageVersion = require('miniaudio_node-openharmony-arm64/package.json').version
        if (bindingPackageVersion !== '1.5.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.5.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'x64') {
      try {
        return require('./miniaudio_node.openharmony-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('miniaudio_node-openharmony-x64')
        const bindingPackageVersion = require('miniaudio_node-openharmony-x64/package.json').version
        if (bindingPackageVersion !== '1.5.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.5.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./miniaudio_node.openharmony-arm.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('miniaudio_node-openharmony-arm')
        const bindingPackageVersion = require('miniaudio_node-openharmony-arm/package.json').version
        if (bindingPackageVersion !== '1.5.1' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 1.5.1 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

nativeBinding = requireNative()

if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
  let wasiBinding = null
  let wasiBindingError = null
  try {
    wasiBinding = require('./miniaudio_node.wasi.cjs')
    nativeBinding = wasiBinding
  } catch (err) {
    if (process.env.NAPI_RS_FORCE_WASI) {
      wasiBindingError = err
    }
  }
  if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
    try {
      wasiBinding = require('miniaudio_node-wasm32-wasi')
      nativeBinding = wasiBinding
    } catch (err) {
      if (process.env.NAPI_RS_FORCE_WASI) {
        if (!wasiBindingError) {
          wasiBindingError = err
        } else {
          wasiBindingError.cause = err
        }
        loadErrors.push(err)
      }
    }
  }
  if (process.env.NAPI_RS_FORCE_WASI === 'error' && !wasiBinding) {
    const error = new Error('WASI binding not found and NAPI_RS_FORCE_WASI is set to error')
    error.cause = wasiBindingError
    throw error
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    throw new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
      {
        cause: loadErrors.reduce((err, cur) => {
          cur.cause = err
          return cur
        }),
      },
    )
  }
  throw new Error(`Failed to load native binding`)
}

module.exports = nativeBinding
module.exports.AudioDecoder = nativeBinding.AudioDecoder
module.exports.AudioPlayer = nativeBinding.AudioPlayer
module.exports.AudioRecorder = nativeBinding.AudioRecorder
module.exports.AudioSourceQueue = nativeBinding.AudioSourceQueue
module.exports.AudioStream = nativeBinding.AudioStream
module.exports.AudioStreamBuilder = nativeBinding.AudioStreamBuilder
module.exports.BlueNoise = nativeBinding.BlueNoise
module.exports.BrownianNoise = nativeBinding.BrownianNoise
module.exports.ChannelCountConverter = nativeBinding.ChannelCountConverter
module.exports.DecoderBuilder = nativeBinding.DecoderBuilder
module.exports.DecoderBuilderSettings = nativeBinding.DecoderBuilderSettings
module.exports.LoopedDecoder = nativeBinding.LoopedDecoder
module.exports.Mixer = nativeBinding.Mixer
module.exports.MixerSource = nativeBinding.MixerSource
module.exports.PinkNoise = nativeBinding.PinkNoise
module.exports.SampleRateConverter = nativeBinding.SampleRateConverter
module.exports.SamplesBuffer = nativeBinding.SamplesBuffer
module.exports.SampleTypeConverter = nativeBinding.SampleTypeConverter
module.exports.SourcesQueueInput = nativeBinding.SourcesQueueInput
module.exports.SourcesQueueOutput = nativeBinding.SourcesQueueOutput
module.exports.StaticSamplesBuffer = nativeBinding.StaticSamplesBuffer
module.exports.VelvetNoise = nativeBinding.VelvetNoise
module.exports.VioletNoise = nativeBinding.VioletNoise
module.exports.WhiteGaussianNoise = nativeBinding.WhiteGaussianNoise
module.exports.WhiteTriangularNoise = nativeBinding.WhiteTriangularNoise
module.exports.WhiteUniformNoise = nativeBinding.WhiteUniformNoise
module.exports.createAudioPlayer = nativeBinding.createAudioPlayer
module.exports.dbToLinear = nativeBinding.dbToLinear
module.exports.DecoderError = nativeBinding.DecoderError
module.exports.DevicesError = nativeBinding.DevicesError
module.exports.getAudioInfo = nativeBinding.getAudioInfo
module.exports.getAudioMetadata = nativeBinding.getAudioMetadata
module.exports.getAvailableHosts = nativeBinding.getAvailableHosts
module.exports.getInputDevices = nativeBinding.getInputDevices
module.exports.getSupportedFormats = nativeBinding.getSupportedFormats
module.exports.initializeAudio = nativeBinding.initializeAudio
module.exports.isDebugEnabled = nativeBinding.isDebugEnabled
module.exports.isFormatSupported = nativeBinding.isFormatSupported
module.exports.linearToDb = nativeBinding.linearToDb
module.exports.mixer = nativeBinding.mixer
module.exports.pink = nativeBinding.pink
module.exports.play = nativeBinding.play
module.exports.PlaybackState = nativeBinding.PlaybackState
module.exports.PlayError = nativeBinding.PlayError
module.exports.queue = nativeBinding.queue
module.exports.quickPlay = nativeBinding.quickPlay
module.exports.SeekError = nativeBinding.SeekError
module.exports.setDebug = nativeBinding.setDebug
module.exports.SourceFunction = nativeBinding.SourceFunction
module.exports.StreamError = nativeBinding.StreamError
module.exports.StreamPlayError = nativeBinding.StreamPlayError
module.exports.supportedOutputConfigs = nativeBinding.supportedOutputConfigs
module.exports.testTone = nativeBinding.testTone
module.exports.white = nativeBinding.white
