/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Audio device information structure */
export interface AudioDeviceInfo {
  id: string
  name: string
  isDefault: boolean
}
/** Audio player state enumeration */
export const enum PlaybackState {
  Stopped = 0,
  Loaded = 1,
  Playing = 2,
  Paused = 3
}
export declare function initializeAudio(): string
export declare function getSupportedFormats(): Array<string>
export declare function isFormatSupported(format: string): boolean
export declare function getAudioInfo(): string
export declare function testTone(frequency: number, durationMs: number): void
export interface AudioPlayerConfig {
  volume?: number
  autoPlay?: boolean
}
export declare function createAudioPlayer(config?: AudioPlayerConfig | undefined | null): AudioPlayer
export declare function quickPlay(filePath: string, config?: AudioPlayerConfig | undefined | null): AudioPlayer
export interface AudioMetadata {
  duration: number
  title?: string
  artist?: string
  album?: string
}
export declare function getAudioMetadata(filePath: string): AudioMetadata
/** Thread-safe audio player with rodio backend */
export declare class AudioPlayer {
  constructor()
  getDevices(): Array<AudioDeviceInfo>
  loadFile(filePath: string): void
  loadBuffer(audioData: Array<number>): void
  loadBase64(base64Data: string): void
  play(): void
  pause(): void
  stop(): void
  setVolume(volume: number): void
  getVolume(): number
  isPlaying(): boolean
  getState(): PlaybackState
  getDuration(): number
  getCurrentTime(): number
  getCurrentFile(): string | null
}
